version: '3'

services:
  monitoring:
    image: fabos4ai/slm-monitoring-prometheus:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    networks:
      default:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
