name: Build Stack

on:
  push:
    branches:
      - main

env:
  DOCKER_COMMAND: docker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        working-directory: ./
        run: $DOCKER_COMMAND image build ./ --no-cache -t ghcr.io/eclipse-slm/slm-monitoring-prometheus-aas:0.0.1-SNAPSHOT
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Push docker image
        working-directory: ./
        run: $DOCKER_COMMAND image push ghcr.io/eclipse-slm/slm-monitoring-prometheus-aas:0.0.1-SNAPSHOT
